export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const EXERCISE_START = "EXERCISE_START";
export const EXERCISE_SUCCESS = "EXERCISE_SUCCESS";
export const EXERCISE_SUCCESS_FETCH = "EXERCISE_SUCCESS_FETCH";
export const EXERCISE_FAIL = "EXERCISE_FAIL";
