# Generated by Django 2.2.3 on 2019-10-12 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exercise.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('uuid', models.CharField(blank=True, default=exercise.models.generate_uuid, max_length=32, null=True)),
                ('password', models.CharField(default='1234', max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='program', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
